services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=guest'
      - 'POSTGRES_USER=guest'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
